FROM node:18 AS builder
COPY yarn.lock package.json ./
COPY . .

FROM node:18-slim AS final
WORKDIR /app
FROM node:18
ENV NODE_ENV=production
WORKDIR /app
RUN yarn install --frozen-lockfile
RUN yarn build
EXPOSE 3000
CMD ["node", "build/server.js"]
