FROM node:18 AS builder
RUN yarn install --frozen-lockfile

FROM node:18-slim AS final
WORKDIR /app
FROM node:18
ENV NODE_ENV=production
WORKDIR /app
COPY yarn.lock package.json ./
COPY . .
RUN yarn build
EXPOSE 3000
CMD ["node", "build/server.js"]
